export type UgandaRegion = "Central" | "Eastern" | "Northern" | "Western";

export interface RegionDistrictGroup {
  region: UgandaRegion;
  districts: string[];
}

export const REGION_DISTRICT_GROUPS: RegionDistrictGroup[] = [
  {
    region: "Central",
    districts: [
      "Buikwe",
      "Bukomansimbi",
      "Buvuma",
      "Butambala",
      "Gomba",
      "Kalangala",
      "Kalungu",
      "Kampala",
      "Kassanda",
      "Kayunga",
      "Kiboga",
      "Kyankwanzi",
      "Kyotera",
      "Luweero",
      "Lwengo",
      "Lyantonde",
      "Masaka",
      "Mityana",
      "Mpigi",
      "Mubende",
      "Mukono",
      "Nakaseke",
      "Nakasongola",
      "Rakai",
      "Sembabule",
      "Wakiso",
    ],
  },
  {
    region: "Eastern",
    districts: [
      "Amuria",
      "Budaka",
      "Bududa",
      "Bugiri",
      "Bugweri",
      "Bukedea",
      "Bukwo",
      "Bulambuli",
      "Busia",
      "Butaleja",
      "Butebo",
      "Buyende",
      "Iganga",
      "Jinja",
      "Kaberamaido",
      "Kalaki",
      "Kaliro",
      "Kamuli",
      "Kapchorwa",
      "Kapelebyong",
      "Katakwi",
      "Kibuku",
      "Kumi",
      "Luuka",
      "Manafwa",
      "Mayuge",
      "Mbale",
      "Namayingo",
      "Namisindwa",
      "Namutumba",
      "Ngora",
      "Pallisa",
      "Serere",
      "Sironko",
      "Soroti",
      "Tororo",
    ],
  },
  {
    region: "Northern",
    districts: [
      "Abim",
      "Adjumani",
      "Agago",
      "Alebtong",
      "Amolatar",
      "Amudat",
      "Amuru",
      "Apac",
      "Arua",
      "Dokolo",
      "Gulu",
      "Kaabong",
      "Karenga",
      "Kitgum",
      "Koboko",
      "Kole",
      "Kotido",
      "Kwania",
      "Lamwo",
      "Lira",
      "Madi-Okollo",
      "Maracha",
      "Moroto",
      "Moyo",
      "Nabilatuk",
      "Nakapiripirit",
      "Napak",
      "Nebbi",
      "Nwoya",
      "Omoro",
      "Otuke",
      "Oyam",
      "Pader",
      "Pakwach",
      "Terego",
      "Obongi",
      "Yumbe",
      "Zombo",
    ],
  },
  {
    region: "Western",
    districts: [
      "Buhweju",
      "Buliisa",
      "Bundibugyo",
      "Bunyangabu",
      "Bushenyi",
      "Hoima",
      "Ibanda",
      "Isingiro",
      "Kabale",
      "Kabarole",
      "Kagadi",
      "Kakumiro",
      "Kamwenge",
      "Kanungu",
      "Kasese",
      "Kazo",
      "Kibaale",
      "Kikuube",
      "Kiruhura",
      "Kiryandongo",
      "Kitagwenda",
      "Kyegegwa",
      "Kyenjojo",
      "Masindi",
      "Mbarara",
      "Mitooma",
      "Ntungamo",
      "Ntoroko",
      "Rubanda",
      "Rubirizi",
      "Rukiga",
      "Rukungiri",
      "Rwampara",
      "Sheema",
      "Kisoro",
    ],
  },
];

export const ALL_DISTRICTS = REGION_DISTRICT_GROUPS.flatMap((group) => group.districts);

export const DISTRICT_TO_REGION = REGION_DISTRICT_GROUPS.reduce<Record<string, UgandaRegion>>((acc, group) => {
  group.districts.forEach((district) => {
    acc[district.toLowerCase()] = group.region;
  });
  return acc;
}, {});

export const findRegionForDistrict = (name: string): UgandaRegion | undefined => {
  return DISTRICT_TO_REGION[name.trim().toLowerCase()];
};
